config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :posts2
  resources :posts3
  resources :posts4
  resources :posts5
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/posts2_controller.rb
class Posts2Controller < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @pagy, @posts = pagy_countless(Post.all, items: 10)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        redirect_to post_url(@post), notice: "Post was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        redirect_to post_url(@post), notice: "Post was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      redirect_to posts_url, notice: "Post was successfully destroyed."
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/posts3_controller.rb
class Posts3Controller < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @pagy, @posts = pagy_countless(Post.all, items: 10)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        redirect_to post_url(@post), notice: "Post was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        redirect_to post_url(@post), notice: "Post was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      redirect_to posts_url, notice: "Post was successfully destroyed."
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/posts4_controller.rb
class Posts4Controller < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @pagy, @posts = pagy_countless(Post.all, items: 10)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        redirect_to post_url(@post), notice: "Post was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        redirect_to post_url(@post), notice: "Post was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      redirect_to posts_url, notice: "Post was successfully destroyed."
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/posts5_controller.rb
class Posts5Controller < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @pagy, @posts = pagy_countless(Post.all, items: 10)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        redirect_to post_url(@post), notice: "Post was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        redirect_to post_url(@post), notice: "Post was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      redirect_to posts_url, notice: "Post was successfully destroyed."
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @pagy, @posts = pagy_countless(Post.all, items: 10)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        redirect_to post_url(@post), notice: "Post was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        redirect_to post_url(@post), notice: "Post was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      redirect_to posts_url, notice: "Post was successfully destroyed."
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Video</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= turbo_refreshes_with method: :morph, scroll: :preserve %>
    <%= yield :head %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, id: 'post_form') do |form| %>

  <fieldset <%= 'disabled' if disabled %>>

  <% if @post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  </fieldset>

<% end %>

app/views/posts/_post.html.erb
<p>
  <strong>
    <%= link_to post.title, post_path(post) %>
  </strong>
</p>

<p>
  <%= post.body %>
</p>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<controls>
  <%= button_tag "Update", form: "post_form", formaction: posts_path(@post), method: :patch %>
  <%= link_to "Back", post_path(@post), role: "button" %>
</controls>

<%= render "form", post: @post, disabled: false %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<controls>
  <%= link_to "New", new_post_path(@post), role: "button" %>
</controls>

<%= turbo_frame_tag :foo do %>
  <% @posts.each do |post| %>
    <%= render "post", post: post %>
  <% end %>
<% end %>

<%= turbo_frame_tag :frame_identifier, 
  loading: :lazy,
  src: posts_path(format: :turbo_stream, page: @pagy.next)
%>

app/views/posts/index.turbo_stream.erb
<%= turbo_stream.append :foo do %>
  <%= render @posts %>
<% end %>

<%= turbo_stream.replace :frame_identifier do %>
  <% if @pagy.next.present? %>
    <%= turbo_frame_tag :frame_identifier, 
      loading: :lazy,
      src: posts_path(format: :turbo_stream, page: @pagy.next)
    %>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<controls>
  <%= button_tag "Create", form: "post_form", formaction: posts_path(@post) %>
  <%= link_to "Back", posts_path, role: "button" %>
</controls>

<%= render "form", disabled: false %>

app/views/posts/show.html.erb
<h1>Post</h1>

<% turbo_page_requires_reload %>

<%= turbo_stream_from @post %>

<controls>
  <%= link_to "Edit", edit_post_path(@post), role: "button" %>
  <%= link_to "Back", posts_path, role: "button" %>
</controls>

<%= render "form", disabled: true %>

app/views/posts2/index.html.erb
<h1>Posts</h1>

<%= turbo_frame_tag :foo do %>
  <% @posts.each do |post| %>
    <p>
      <strong>
        <%= post.title %>
      </strong>
    </p>
    <p>
      <%= post.body %>
    </p>
  <% end %>
<% end %>

<%= turbo_frame_tag :frame_identifier, 
  loading: :lazy,
  src: posts2_index_path(format: :turbo_stream, page: @pagy.next)
%>

app/views/posts2/index.turbo_stream.erb
<%= turbo_stream.append :foo do %>
  <% @posts.each do |post| %>
    <p>
      <strong>
        <%= post.title %>
      </strong>
    </p>
    <p>
      <%= post.body %>
    </p>
  <% end %>
<% end %>

<%= turbo_stream.replace :frame_identifier do %>
  <% if @pagy.next.present? %>
    <%= turbo_frame_tag :frame_identifier, 
      loading: :lazy,
      src: posts2_index_path(format: :turbo_stream, page: @pagy.next)
    %>
  <% end %>
<% end %>

app/views/posts3/index.html.erb
<h1>Posts</h1>

<turbo-frame id="foo" loading="lazy">
  <% @posts.each do |post| %>
    <p>
      <%= post.id %>
    </p>
    <p>
      <%= post.title %>
    </p>
  <% end %>
</turbo-frame>

<%= turbo_frame_tag :foo2, 
  loading: :lazy,
  src: posts3_index_path(format: :turbo_stream, page: @pagy.next)
%>

app/views/posts3/index.turbo_stream.erb
<%= turbo_stream.append :foo do %>

  <% @posts.each do |post| %>
    <p>
      <%= post.id %>
    </p>
    <p>
      <%= post.title %>
    </p>
  <% end %>
<% end %>

<%= turbo_stream.replace :foo2 do %>
  <% if @pagy.next.present? %>
    <%= turbo_frame_tag :foo2, 
      loading: :lazy,
      src: posts3_index_path(format: :turbo_stream, page: @pagy.next)
    %>
  <% end %>
<% end %>

app/views/posts4/index.html.erb
<style>

[table] {
  display: table;
  width: 100%;
  border-collapse: collapse;
}

row {
  display: table-row;
}

cell {
  display: table-cell;
}

</style>

<h1>Posts</h1>

<turbo-frame id="foo" loading="lazy" table>
  <row>
    <cell>
      id 
    </cell>
    <cell>
      title 
    </cell>
  </row>
  <% @posts.each do |post| %>
    <row>
      <cell>
        <%= post.id %>
      </cell>
      <cell>
        <%= post.title %>
      </cell>
    </row>
  <% end %>
</turbo-frame>

<%= turbo_frame_tag :foo2, 
  loading: :lazy,
  src: posts4_index_path(format: :turbo_stream, page: @pagy.next)
%>

app/views/posts4/index.turbo_stream.erb
<%= turbo_stream.append :foo do %>
  <% @posts.each do |post| %>
    <row>
      <cell>
        <%= post.id %>
      </cell>
      <cell>
        <%= post.title %>
      </cell>
    </row>
  <% end %>
<% end %>

<%= turbo_stream.replace :foo2 do %>
  <% if @pagy.next.present? %>
    <%= turbo_frame_tag :foo2, 
      loading: :lazy,
      src: posts4_index_path(format: :turbo_stream, page: @pagy.next)
    %>
  <% end %>
<% end %>

app/views/posts5/index.html.erb
<style>

table {
  width: 100%;
  border-collapse: collapse;
}

</style>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>
        id 
      </th>
      <th>
        title 
      </th>
    </tr>
  </thead>
  <tbody id="foo" is="turbo-frame">
    <% @posts.each do |post| %>
      <tr>
        <td>
          <%= post.id %>
        </td>
        <td>
          <%= post.title %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= turbo_frame_tag :foo2, 
  loading: :lazy,
  src: posts5_index_path(format: :turbo_stream, page: @pagy.next)
%>

app/views/posts5/index.turbo_stream.erb
<%= turbo_stream.append :foo do %>
  <% @posts.each do |post| %>
    <tr is="turbo-frame">
      <td>
        <%= post.id %>
      <td>
      <td>
        <%= post.title %>
      </td>
    </tr>
  <% end %>
<% end %>

<%= turbo_stream.replace :foo2 do %>
  <% if @pagy.next.present? %>
    <%= turbo_frame_tag :foo2, 
      loading: :lazy,
      src: posts5_index_path(format: :turbo_stream, page: @pagy.next)
    %>
  <% end %>
<% end %>